//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 08:31:08 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deppon.com/uums/inteface/domain/usermanagement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = {@XmlNs(prefix = "dpap", namespaceURI = "http://www.deppon.com/dpap/excel/tmp/")})
package com.deppon.dpap.module.sync.business.jms;
import javax.xml.bind.annotation.XmlNs;  
import javax.xml.bind.annotation.XmlSchema;
