
DROP TABLE IF EXISTS t_esb_svcpoint;
CREATE TABLE t_esb_svcpoint (
  FID varchar(36) NOT NULL,
  NAME varchar(80) DEFAULT NULL,
  CODE varchar(80) NOT NULL,
  SYSID varchar(10) DEFAULT NULL,
  AGRMT varchar(80) DEFAULT NULL,
  FRNTORBCK char(1) DEFAULT NULL,
  APPREQUESTADDR varchar(100) DEFAULT NULL,
  APPRESPONSEADDR varchar(100) DEFAULT NULL,
  ESBREQUESTADDR varchar(100) DEFAULT NULL,
  ESBRESPONSEADDR varchar(100) DEFAULT NULL,
  EXPATTERN int(1) DEFAULT NULL,
  MESSAGEFORMAT varchar(80) DEFAULT NULL,
  TIMEOUT int(9) DEFAULT NULL,
  REQCONVERTORCLASS varchar(400) DEFAULT NULL,
  RESCONVERTORCLASS varchar(400) DEFAULT NULL,
  WSPORTNAME varchar(200) DEFAULT NULL,
  WSSERVICENAME varchar(200) DEFAULT NULL,
  WSTARGETNAMESPACE varchar(500) DEFAULT NULL,
  NEEDAUDIT char(1) DEFAULT '1',
  NEEDEXPN char(1) DEFAULT '1',
  NEEDSTATUS char(1) DEFAULT '1',
  ACTIVE char(1) NOT NULL DEFAULT '1',
  CREATETIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATETIME timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  component varchar(255) NOT NULL,
  PRIMARY KEY (FID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO t_esb_svcpoint VALUES ('2', '测试1', 'hbhk2', 'HBHK', 'restful', 'B', '', '', 'http://www.baidu.com', '', '1', 'restful', '60000', '', '', '', '', '', '1', '1', '1', '1', '2015-09-08 10:32:06', '2015-09-08 10:32:06', '');
INSERT INTO t_esb_svcpoint VALUES ('1', '测试1', 'hbhk1', 'HBHK', '', 'B', 'QU_HBHK_REQUEST_COM_IN', 'RQ_HBHK_RESPONSE_COM_OUT', 'RQ_HBHK_REQUEST_COM_IN', '', '2', 'XML', '60000', '', '', '', '', '', '1', '1', '1', '1', '2015-09-08 10:56:17', '2015-09-08 10:56:17', 'ESBMQ');
